name: Delf's test Pages page
markdown: kramdown


safe: true
exclude: [ "README.md", "CNAME" ]
TZ: "America/Los_Angeles"

destination: ./_site/haystack
baseurl: "/haystack"

collections_dir: ./src
collections:
  src:
    output: true

